name: Build Guix WSL2 image

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          pullAfterInstall: true

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build WSL image
        id: wsl-image-builder
        run: echo "WSL_IMAGE_PATH=$(guix system image --image-type=wsl2 --expression='(@ (gnu system images wsl2) wsl-os)')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        id: docker-image-builder
        run: echo "DOCKER_IMAGE_PATH=$(guix system image --image-type=docker /etc/current-system.scm)" >> $GITHUB_OUTPUT

      - name: Set time
        run: echo "NOW=$(date +'%Y-%m')" >> $GITHUB_ENV
      
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ steps.wsl-image-builder.outputs.WSL_IMAGE_PATH }}
            ${{ steps.docker-image-builder.outputs.DOCKER_IMAGE_PATH }}
          tag_name: ${{ env.NOW }}
