name: Build Guix WSL2 image

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          pullAfterInstall: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the image
        id: image-builder
        run: echo "IMAGE_PATH=$(guix system image --image-type=wsl2 --expression='(@ (gnu system images wsl2) wsl-os)')" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.image-builder.outputs.IMAGE_PATH }}
          tag_name: $(date +'%Y-%m-%d')
